name: PR - Bicep WhatIf

on:
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/**"
      - ".github/workflows/*bicep*.yml"
      - ".github/workflows/pr.yml"

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  bicep-whatif-dev:
    name: Bicep Whatif Dev
    uses: ./.github/workflows/step-bicep-whatif.yml
    with:
      env: dev
      resource_group_name: rg-workshop-dnazghbicep-dev
    secrets:
      azure_client_id: ${{ secrets.DEV_AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.DEV_AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}
