# This sample is derived from https://github.com/Azure-Samples/bicep-github-actions/blob/5f50d73f4830fbd8d864adf5bac32b3f192c7977/.github/workflows/bicep-whatif-deploy.yml
name: "Step - Bicep WhatIf"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
    secrets:
      azure_client_id:
        required: true
        description: "Client ID for Azure Service Principal"
      azure_subscription_id:
        required: true
        description: "Azure Subscription ID for the targeted Resource Group"
      azure_tenant_id:
        required: true
        description: "Azure Tenant ID for the targeted Resource Group"

jobs:
  bicep-whatif:
    name: Bicep WhatIf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Bicep Build
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep build --file infrastructure/main.bicep

      - name: Bicep Validate
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment group validate \
              --name validate-${{ github.run_id }} \
              --template-file infrastructure/main.bicep \
              --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
              --resource-group ${{ inputs.resource_group_name }}

      # Perform a security scan of the bicep code using checkov
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: bicep
          skip_check: CKV_AZURE_17,CKV_AZURE_80,CKV_AZURE_13,CKV_AZURE_88,CKV_AZURE_66,CKV_AZURE_65,CKV_AZURE_63

      - name: WhatIf
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment group what-if \
              --name whatif-${{ github.run_id }} \
              --template-file infrastructure/main.bicep \
              --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
              --resource-group ${{ inputs.resource_group_name }} > whatif.txt

        # Create string output of Whatif
      - name: Create String Output
        id: whatif-string
        run: |
          WHATIF=$(cat whatif.txt)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Whatif Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "$WHATIF" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Whatif to Task Summary
        env:
          SUMMARY: ${{ steps.whatif-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      # If this is a PR post the changes
      - name: Push Whatif Output to PR
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@v6
        env:
          SUMMARY: "${{ steps.whatif-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })
